<?php
/**
 * ApiDefinitionsGetCollection200ResponseHydraView
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JsonHub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * ApiDefinitionsGetCollection200ResponseHydraView Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ApiDefinitionsGetCollection200ResponseHydraView implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'api_definitions_get_collection_200_response_hydra_view';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'at_id' => 'string',
        'at_type' => 'string',
        'hydra_first' => 'string',
        'hydra_last' => 'string',
        'hydra_previous' => 'string',
        'hydra_next' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'at_id' => 'iri-reference',
        'at_type' => null,
        'hydra_first' => 'iri-reference',
        'hydra_last' => 'iri-reference',
        'hydra_previous' => 'iri-reference',
        'hydra_next' => 'iri-reference'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'at_id' => false,
        'at_type' => false,
        'hydra_first' => false,
        'hydra_last' => false,
        'hydra_previous' => false,
        'hydra_next' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'at_id' => '@id',
        'at_type' => '@type',
        'hydra_first' => 'hydra:first',
        'hydra_last' => 'hydra:last',
        'hydra_previous' => 'hydra:previous',
        'hydra_next' => 'hydra:next'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'at_id' => 'setAtId',
        'at_type' => 'setAtType',
        'hydra_first' => 'setHydraFirst',
        'hydra_last' => 'setHydraLast',
        'hydra_previous' => 'setHydraPrevious',
        'hydra_next' => 'setHydraNext'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'at_id' => 'getAtId',
        'at_type' => 'getAtType',
        'hydra_first' => 'getHydraFirst',
        'hydra_last' => 'getHydraLast',
        'hydra_previous' => 'getHydraPrevious',
        'hydra_next' => 'getHydraNext'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('at_id', $data ?? [], null);
        $this->setIfExists('at_type', $data ?? [], null);
        $this->setIfExists('hydra_first', $data ?? [], null);
        $this->setIfExists('hydra_last', $data ?? [], null);
        $this->setIfExists('hydra_previous', $data ?? [], null);
        $this->setIfExists('hydra_next', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets at_id
     *
     * @return string|null
     */
    public function getAtId(): ?string
    {
        return $this->container['at_id'];
    }

    /**
     * Sets at_id
     *
     * @param string|null $at_id at_id
     *
     * @return $this
     */
    public function setAtId(?string $at_id): static
    {
        if (is_null($at_id)) {
            throw new InvalidArgumentException('non-nullable at_id cannot be null');
        }
        $this->container['at_id'] = $at_id;

        return $this;
    }

    /**
     * Gets at_type
     *
     * @return string|null
     */
    public function getAtType(): ?string
    {
        return $this->container['at_type'];
    }

    /**
     * Sets at_type
     *
     * @param string|null $at_type at_type
     *
     * @return $this
     */
    public function setAtType(?string $at_type): static
    {
        if (is_null($at_type)) {
            throw new InvalidArgumentException('non-nullable at_type cannot be null');
        }
        $this->container['at_type'] = $at_type;

        return $this;
    }

    /**
     * Gets hydra_first
     *
     * @return string|null
     */
    public function getHydraFirst(): ?string
    {
        return $this->container['hydra_first'];
    }

    /**
     * Sets hydra_first
     *
     * @param string|null $hydra_first hydra_first
     *
     * @return $this
     */
    public function setHydraFirst(?string $hydra_first): static
    {
        if (is_null($hydra_first)) {
            throw new InvalidArgumentException('non-nullable hydra_first cannot be null');
        }
        $this->container['hydra_first'] = $hydra_first;

        return $this;
    }

    /**
     * Gets hydra_last
     *
     * @return string|null
     */
    public function getHydraLast(): ?string
    {
        return $this->container['hydra_last'];
    }

    /**
     * Sets hydra_last
     *
     * @param string|null $hydra_last hydra_last
     *
     * @return $this
     */
    public function setHydraLast(?string $hydra_last): static
    {
        if (is_null($hydra_last)) {
            throw new InvalidArgumentException('non-nullable hydra_last cannot be null');
        }
        $this->container['hydra_last'] = $hydra_last;

        return $this;
    }

    /**
     * Gets hydra_previous
     *
     * @return string|null
     */
    public function getHydraPrevious(): ?string
    {
        return $this->container['hydra_previous'];
    }

    /**
     * Sets hydra_previous
     *
     * @param string|null $hydra_previous hydra_previous
     *
     * @return $this
     */
    public function setHydraPrevious(?string $hydra_previous): static
    {
        if (is_null($hydra_previous)) {
            throw new InvalidArgumentException('non-nullable hydra_previous cannot be null');
        }
        $this->container['hydra_previous'] = $hydra_previous;

        return $this;
    }

    /**
     * Gets hydra_next
     *
     * @return string|null
     */
    public function getHydraNext(): ?string
    {
        return $this->container['hydra_next'];
    }

    /**
     * Sets hydra_next
     *
     * @param string|null $hydra_next hydra_next
     *
     * @return $this
     */
    public function setHydraNext(?string $hydra_next): static
    {
        if (is_null($hydra_next)) {
            throw new InvalidArgumentException('non-nullable hydra_next cannot be null');
        }
        $this->container['hydra_next'] = $hydra_next;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


