<?php
/**
 * EntityApi
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JsonHub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * EntityApi Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EntityApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiEntitiesGetCollection' => [
            'application/json',
        ],
        'apiEntitiesIdDelete' => [
            'application/json',
        ],
        'apiEntitiesIdGet' => [
            'application/json',
        ],
        'apiEntitiesIdPatch' => [
            'application/merge-patch+json',
        ],
        'apiEntitiesPost' => [
            'application/ld+json',
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation apiEntitiesGetCollection
     *
     * Retrieves the collection of entity resources.
     *
     * @param  string|null $qid Filter by slug/id (partial match) (optional)
     * @param  bool|null $private Show only private entities (owned by the current user) (optional)
     * @param  bool|null $is_owned_by_me Show only entities owned by the current user (optional)
     * @param  int|null $page The collection page number (optional, default to 1)
     * @param  int|null $limit The number of items per page (optional, default to 10)
     * @param  string[]|null $properties Allows you to reduce the response to contain only the properties you need. If your desired property is nested, you can address it using nested arrays. Example: properties[]&#x3D;{propertyName}&amp;properties[]&#x3D;{anotherPropertyName}&amp;properties[{nestedPropertyParent}][]&#x3D;{nestedProperty} (optional)
     * @param  string|null $definition Filter by definition (uuid) (optional)
     * @param  string|null $parent Filter by parent (uuid) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesGetCollection'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\ApiEntitiesGetCollection200Response
     */
    public function apiEntitiesGetCollection(
        ?string $qid = null,
        ?bool $private = null,
        ?bool $is_owned_by_me = null,
        ?int $page = 1,
        ?int $limit = 10,
        ?array $properties = null,
        ?string $definition = null,
        ?string $parent = null,
        string $contentType = self::contentTypes['apiEntitiesGetCollection'][0]
    ): \OpenAPI\Client\Model\ApiEntitiesGetCollection200Response
    {
        list($response) = $this->apiEntitiesGetCollectionWithHttpInfo($qid, $private, $is_owned_by_me, $page, $limit, $properties, $definition, $parent, $contentType);
        return $response;
    }

    /**
     * Operation apiEntitiesGetCollectionWithHttpInfo
     *
     * Retrieves the collection of entity resources.
     *
     * @param  string|null $qid Filter by slug/id (partial match) (optional)
     * @param  bool|null $private Show only private entities (owned by the current user) (optional)
     * @param  bool|null $is_owned_by_me Show only entities owned by the current user (optional)
     * @param  int|null $page The collection page number (optional, default to 1)
     * @param  int|null $limit The number of items per page (optional, default to 10)
     * @param  string[]|null $properties Allows you to reduce the response to contain only the properties you need. If your desired property is nested, you can address it using nested arrays. Example: properties[]&#x3D;{propertyName}&amp;properties[]&#x3D;{anotherPropertyName}&amp;properties[{nestedPropertyParent}][]&#x3D;{nestedProperty} (optional)
     * @param  string|null $definition Filter by definition (uuid) (optional)
     * @param  string|null $parent Filter by parent (uuid) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesGetCollection'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ApiEntitiesGetCollection200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiEntitiesGetCollectionWithHttpInfo(
        ?string $qid = null,
        ?bool $private = null,
        ?bool $is_owned_by_me = null,
        ?int $page = 1,
        ?int $limit = 10,
        ?array $properties = null,
        ?string $definition = null,
        ?string $parent = null,
        string $contentType = self::contentTypes['apiEntitiesGetCollection'][0]
    ): array
    {
        $request = $this->apiEntitiesGetCollectionRequest($qid, $private, $is_owned_by_me, $page, $limit, $properties, $definition, $parent, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\OpenAPI\Client\Model\ApiEntitiesGetCollection200Response', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ApiEntitiesGetCollection200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ApiEntitiesGetCollection200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\ApiEntitiesGetCollection200Response';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ApiEntitiesGetCollection200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiEntitiesGetCollectionAsync
     *
     * Retrieves the collection of entity resources.
     *
     * @param  string|null $qid Filter by slug/id (partial match) (optional)
     * @param  bool|null $private Show only private entities (owned by the current user) (optional)
     * @param  bool|null $is_owned_by_me Show only entities owned by the current user (optional)
     * @param  int|null $page The collection page number (optional, default to 1)
     * @param  int|null $limit The number of items per page (optional, default to 10)
     * @param  string[]|null $properties Allows you to reduce the response to contain only the properties you need. If your desired property is nested, you can address it using nested arrays. Example: properties[]&#x3D;{propertyName}&amp;properties[]&#x3D;{anotherPropertyName}&amp;properties[{nestedPropertyParent}][]&#x3D;{nestedProperty} (optional)
     * @param  string|null $definition Filter by definition (uuid) (optional)
     * @param  string|null $parent Filter by parent (uuid) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesGetCollection'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesGetCollectionAsync(
        ?string $qid = null,
        ?bool $private = null,
        ?bool $is_owned_by_me = null,
        ?int $page = 1,
        ?int $limit = 10,
        ?array $properties = null,
        ?string $definition = null,
        ?string $parent = null,
        string $contentType = self::contentTypes['apiEntitiesGetCollection'][0]
    ): PromiseInterface
    {
        return $this->apiEntitiesGetCollectionAsyncWithHttpInfo($qid, $private, $is_owned_by_me, $page, $limit, $properties, $definition, $parent, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiEntitiesGetCollectionAsyncWithHttpInfo
     *
     * Retrieves the collection of entity resources.
     *
     * @param  string|null $qid Filter by slug/id (partial match) (optional)
     * @param  bool|null $private Show only private entities (owned by the current user) (optional)
     * @param  bool|null $is_owned_by_me Show only entities owned by the current user (optional)
     * @param  int|null $page The collection page number (optional, default to 1)
     * @param  int|null $limit The number of items per page (optional, default to 10)
     * @param  string[]|null $properties Allows you to reduce the response to contain only the properties you need. If your desired property is nested, you can address it using nested arrays. Example: properties[]&#x3D;{propertyName}&amp;properties[]&#x3D;{anotherPropertyName}&amp;properties[{nestedPropertyParent}][]&#x3D;{nestedProperty} (optional)
     * @param  string|null $definition Filter by definition (uuid) (optional)
     * @param  string|null $parent Filter by parent (uuid) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesGetCollection'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesGetCollectionAsyncWithHttpInfo(
        ?string $qid = null,
        ?bool $private = null,
        ?bool $is_owned_by_me = null,
        ?int $page = 1,
        ?int $limit = 10,
        ?array $properties = null,
        ?string $definition = null,
        ?string $parent = null,
        string $contentType = self::contentTypes['apiEntitiesGetCollection'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\ApiEntitiesGetCollection200Response';
        $request = $this->apiEntitiesGetCollectionRequest($qid, $private, $is_owned_by_me, $page, $limit, $properties, $definition, $parent, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiEntitiesGetCollection'
     *
     * @param  string|null $qid Filter by slug/id (partial match) (optional)
     * @param  bool|null $private Show only private entities (owned by the current user) (optional)
     * @param  bool|null $is_owned_by_me Show only entities owned by the current user (optional)
     * @param  int|null $page The collection page number (optional, default to 1)
     * @param  int|null $limit The number of items per page (optional, default to 10)
     * @param  string[]|null $properties Allows you to reduce the response to contain only the properties you need. If your desired property is nested, you can address it using nested arrays. Example: properties[]&#x3D;{propertyName}&amp;properties[]&#x3D;{anotherPropertyName}&amp;properties[{nestedPropertyParent}][]&#x3D;{nestedProperty} (optional)
     * @param  string|null $definition Filter by definition (uuid) (optional)
     * @param  string|null $parent Filter by parent (uuid) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesGetCollection'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiEntitiesGetCollectionRequest(
        ?string $qid = null,
        ?bool $private = null,
        ?bool $is_owned_by_me = null,
        ?int $page = 1,
        ?int $limit = 10,
        ?array $properties = null,
        ?string $definition = null,
        ?string $parent = null,
        string $contentType = self::contentTypes['apiEntitiesGetCollection'][0]
    ): Request
    {





        if ($limit !== null && $limit < 0) {
            throw new InvalidArgumentException('invalid value for "$limit" when calling EntityApi.apiEntitiesGetCollection, must be bigger than or equal to 0.');
        }
        




        $resourcePath = '/api/entities';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $qid,
            'qid', // param base name
            'string', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $private,
            'private', // param base name
            'boolean', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $is_owned_by_me,
            'isOwnedByMe', // param base name
            'boolean', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $properties,
            'properties[]', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $definition,
            'definition', // param base name
            'string', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $parent,
            'parent', // param base name
            'string', // openApiType
            'form', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiEntitiesIdDelete
     *
     * Removes the entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function apiEntitiesIdDelete(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdDelete'][0]
    ): void
    {
        $this->apiEntitiesIdDeleteWithHttpInfo($id, $contentType);
    }

    /**
     * Operation apiEntitiesIdDeleteWithHttpInfo
     *
     * Removes the entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiEntitiesIdDeleteWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdDelete'][0]
    ): array
    {
        $request = $this->apiEntitiesIdDeleteRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiEntitiesIdDeleteAsync
     *
     * Removes the entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesIdDeleteAsync(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdDelete'][0]
    ): PromiseInterface
    {
        return $this->apiEntitiesIdDeleteAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiEntitiesIdDeleteAsyncWithHttpInfo
     *
     * Removes the entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesIdDeleteAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdDelete'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->apiEntitiesIdDeleteRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiEntitiesIdDelete'
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiEntitiesIdDeleteRequest(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdDelete'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling apiEntitiesIdDelete'
            );
        }


        $resourcePath = '/api/entities/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiEntitiesIdGet
     *
     * Retrieves a entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent
     */
    public function apiEntitiesIdGet(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdGet'][0]
    ): \OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent
    {
        list($response) = $this->apiEntitiesIdGetWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation apiEntitiesIdGetWithHttpInfo
     *
     * Retrieves a entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdGet'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiEntitiesIdGetWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdGet'][0]
    ): array
    {
        $request = $this->apiEntitiesIdGetRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiEntitiesIdGetAsync
     *
     * Retrieves a entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesIdGetAsync(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdGet'][0]
    ): PromiseInterface
    {
        return $this->apiEntitiesIdGetAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiEntitiesIdGetAsyncWithHttpInfo
     *
     * Retrieves a entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesIdGetAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdGet'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent';
        $request = $this->apiEntitiesIdGetRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiEntitiesIdGet'
     *
     * @param  string $id entity identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdGet'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiEntitiesIdGetRequest(
        string $id,
        string $contentType = self::contentTypes['apiEntitiesIdGet'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling apiEntitiesIdGet'
            );
        }


        $resourcePath = '/api/entities/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiEntitiesIdPatch
     *
     * Updates the entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update The updated entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdPatch'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent
     */
    public function apiEntitiesIdPatch(
        string $id,
        \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update,
        string $contentType = self::contentTypes['apiEntitiesIdPatch'][0]
    ): \OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent
    {
        list($response) = $this->apiEntitiesIdPatchWithHttpInfo($id, $entity_entity_update, $contentType);
        return $response;
    }

    /**
     * Operation apiEntitiesIdPatchWithHttpInfo
     *
     * Updates the entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update The updated entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdPatch'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiEntitiesIdPatchWithHttpInfo(
        string $id,
        \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update,
        string $contentType = self::contentTypes['apiEntitiesIdPatch'][0]
    ): array
    {
        $request = $this->apiEntitiesIdPatchRequest($id, $entity_entity_update, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiEntitiesIdPatchAsync
     *
     * Updates the entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update The updated entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdPatch'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesIdPatchAsync(
        string $id,
        \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update,
        string $contentType = self::contentTypes['apiEntitiesIdPatch'][0]
    ): PromiseInterface
    {
        return $this->apiEntitiesIdPatchAsyncWithHttpInfo($id, $entity_entity_update, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiEntitiesIdPatchAsyncWithHttpInfo
     *
     * Updates the entity resource.
     *
     * @param  string $id entity identifier (required)
     * @param  \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update The updated entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdPatch'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesIdPatchAsyncWithHttpInfo(
        string $id,
        \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update,
        string $contentType = self::contentTypes['apiEntitiesIdPatch'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent';
        $request = $this->apiEntitiesIdPatchRequest($id, $entity_entity_update, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiEntitiesIdPatch'
     *
     * @param  string $id entity identifier (required)
     * @param  \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update The updated entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesIdPatch'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiEntitiesIdPatchRequest(
        string $id,
        \OpenAPI\Client\Model\EntityEntityUpdate $entity_entity_update,
        string $contentType = self::contentTypes['apiEntitiesIdPatch'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling apiEntitiesIdPatch'
            );
        }

        // verify the required parameter 'entity_entity_update' is set
        if ($entity_entity_update === null || (is_array($entity_entity_update) && count($entity_entity_update) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $entity_entity_update when calling apiEntitiesIdPatch'
            );
        }


        $resourcePath = '/api/entities/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($entity_entity_update)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($entity_entity_update));
            } else {
                $httpBody = $entity_entity_update;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiEntitiesPost
     *
     * Creates a entity resource.
     *
     * @param  \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create The new entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent
     */
    public function apiEntitiesPost(
        \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create,
        string $contentType = self::contentTypes['apiEntitiesPost'][0]
    ): \OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent
    {
        list($response) = $this->apiEntitiesPostWithHttpInfo($entity_jsonld_entity_create, $contentType);
        return $response;
    }

    /**
     * Operation apiEntitiesPostWithHttpInfo
     *
     * Creates a entity resource.
     *
     * @param  \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create The new entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiEntitiesPostWithHttpInfo(
        \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create,
        string $contentType = self::contentTypes['apiEntitiesPost'][0]
    ): array
    {
        $request = $this->apiEntitiesPostRequest($entity_jsonld_entity_create, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if (in_array('\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiEntitiesPostAsync
     *
     * Creates a entity resource.
     *
     * @param  \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create The new entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesPostAsync(
        \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create,
        string $contentType = self::contentTypes['apiEntitiesPost'][0]
    ): PromiseInterface
    {
        return $this->apiEntitiesPostAsyncWithHttpInfo($entity_jsonld_entity_create, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiEntitiesPostAsyncWithHttpInfo
     *
     * Creates a entity resource.
     *
     * @param  \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create The new entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiEntitiesPostAsyncWithHttpInfo(
        \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create,
        string $contentType = self::contentTypes['apiEntitiesPost'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\EntityJsonldEntityReadEntityReadParent';
        $request = $this->apiEntitiesPostRequest($entity_jsonld_entity_create, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiEntitiesPost'
     *
     * @param  \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create The new entity resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiEntitiesPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiEntitiesPostRequest(
        \OpenAPI\Client\Model\EntityJsonldEntityCreate $entity_jsonld_entity_create,
        string $contentType = self::contentTypes['apiEntitiesPost'][0]
    ): Request
    {

        // verify the required parameter 'entity_jsonld_entity_create' is set
        if ($entity_jsonld_entity_create === null || (is_array($entity_jsonld_entity_create) && count($entity_jsonld_entity_create) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $entity_jsonld_entity_create when calling apiEntitiesPost'
            );
        }


        $resourcePath = '/api/entities';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($entity_jsonld_entity_create)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($entity_jsonld_entity_create));
            } else {
                $httpBody = $entity_jsonld_entity_create;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
