<?php
/**
 * Oauth2Api
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JsonHub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * Oauth2Api Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Oauth2Api
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiOauth2tokenPost' => [
            'application/ld+json',
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation apiOauth2tokenPost
     *
     * Retrieve an OAuth2 Token
     *
     * @param  \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write The new oauth2 resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiOauth2tokenPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\Oauth2JsonldOauth2Read
     */
    public function apiOauth2tokenPost(
        \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write,
        string $contentType = self::contentTypes['apiOauth2tokenPost'][0]
    ): \OpenAPI\Client\Model\Oauth2JsonldOauth2Read
    {
        list($response) = $this->apiOauth2tokenPostWithHttpInfo($oauth2_jsonld_oauth2_write, $contentType);
        return $response;
    }

    /**
     * Operation apiOauth2tokenPostWithHttpInfo
     *
     * Retrieve an OAuth2 Token
     *
     * @param  \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write The new oauth2 resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiOauth2tokenPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Oauth2JsonldOauth2Read, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiOauth2tokenPostWithHttpInfo(
        \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write,
        string $contentType = self::contentTypes['apiOauth2tokenPost'][0]
    ): array
    {
        $request = $this->apiOauth2tokenPostRequest($oauth2_jsonld_oauth2_write, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if (in_array('\OpenAPI\Client\Model\Oauth2JsonldOauth2Read', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\Oauth2JsonldOauth2Read' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Oauth2JsonldOauth2Read', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\Oauth2JsonldOauth2Read';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Oauth2JsonldOauth2Read',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiOauth2tokenPostAsync
     *
     * Retrieve an OAuth2 Token
     *
     * @param  \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write The new oauth2 resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiOauth2tokenPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiOauth2tokenPostAsync(
        \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write,
        string $contentType = self::contentTypes['apiOauth2tokenPost'][0]
    ): PromiseInterface
    {
        return $this->apiOauth2tokenPostAsyncWithHttpInfo($oauth2_jsonld_oauth2_write, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiOauth2tokenPostAsyncWithHttpInfo
     *
     * Retrieve an OAuth2 Token
     *
     * @param  \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write The new oauth2 resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiOauth2tokenPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiOauth2tokenPostAsyncWithHttpInfo(
        \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write,
        string $contentType = self::contentTypes['apiOauth2tokenPost'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\Oauth2JsonldOauth2Read';
        $request = $this->apiOauth2tokenPostRequest($oauth2_jsonld_oauth2_write, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiOauth2tokenPost'
     *
     * @param  \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write The new oauth2 resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiOauth2tokenPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiOauth2tokenPostRequest(
        \OpenAPI\Client\Model\Oauth2JsonldOauth2Write $oauth2_jsonld_oauth2_write,
        string $contentType = self::contentTypes['apiOauth2tokenPost'][0]
    ): Request
    {

        // verify the required parameter 'oauth2_jsonld_oauth2_write' is set
        if ($oauth2_jsonld_oauth2_write === null || (is_array($oauth2_jsonld_oauth2_write) && count($oauth2_jsonld_oauth2_write) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $oauth2_jsonld_oauth2_write when calling apiOauth2tokenPost'
            );
        }


        $resourcePath = '/api/oauth2/token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($oauth2_jsonld_oauth2_write)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($oauth2_jsonld_oauth2_write));
            } else {
                $httpBody = $oauth2_jsonld_oauth2_write;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
