<?php
/**
 * UserApi
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * JsonHub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * UserApi Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiUsersIdDelete' => [
            'application/json',
        ],
        'apiUsersIdPatch' => [
            'application/merge-patch+json',
        ],
        'apiUsersPost' => [
            'application/ld+json',
            'application/json',
        ],
        'apiUsersresendActivationPost' => [
            'application/ld+json',
            'application/json',
        ],
        'apiUsersresetPasswordPost' => [
            'application/ld+json',
            'application/json',
        ],
        'apiUserssendResetPasswordPost' => [
            'application/ld+json',
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation apiUsersIdDelete
     *
     * Removes the user resource.
     *
     * @param  string $id user identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return void
     */
    public function apiUsersIdDelete(
        string $id,
        string $contentType = self::contentTypes['apiUsersIdDelete'][0]
    ): void
    {
        $this->apiUsersIdDeleteWithHttpInfo($id, $contentType);
    }

    /**
     * Operation apiUsersIdDeleteWithHttpInfo
     *
     * Removes the user resource.
     *
     * @param  string $id user identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdDelete'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiUsersIdDeleteWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['apiUsersIdDelete'][0]
    ): array
    {
        $request = $this->apiUsersIdDeleteRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiUsersIdDeleteAsync
     *
     * Removes the user resource.
     *
     * @param  string $id user identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersIdDeleteAsync(
        string $id,
        string $contentType = self::contentTypes['apiUsersIdDelete'][0]
    ): PromiseInterface
    {
        return $this->apiUsersIdDeleteAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiUsersIdDeleteAsyncWithHttpInfo
     *
     * Removes the user resource.
     *
     * @param  string $id user identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersIdDeleteAsyncWithHttpInfo(
        string $id,
        string $contentType = self::contentTypes['apiUsersIdDelete'][0]
    ): PromiseInterface
    {
        $returnType = '';
        $request = $this->apiUsersIdDeleteRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiUsersIdDelete'
     *
     * @param  string $id user identifier (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdDelete'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiUsersIdDeleteRequest(
        string $id,
        string $contentType = self::contentTypes['apiUsersIdDelete'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling apiUsersIdDelete'
            );
        }


        $resourcePath = '/api/users/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiUsersIdPatch
     *
     * Updates the user resource.
     *
     * @param  string $id user identifier (required)
     * @param  \OpenAPI\Client\Model\UserUserUpdate $user_user_update The updated user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdPatch'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\UserJsonldUserEmpty
     */
    public function apiUsersIdPatch(
        string $id,
        \OpenAPI\Client\Model\UserUserUpdate $user_user_update,
        string $contentType = self::contentTypes['apiUsersIdPatch'][0]
    ): \OpenAPI\Client\Model\UserJsonldUserEmpty
    {
        list($response) = $this->apiUsersIdPatchWithHttpInfo($id, $user_user_update, $contentType);
        return $response;
    }

    /**
     * Operation apiUsersIdPatchWithHttpInfo
     *
     * Updates the user resource.
     *
     * @param  string $id user identifier (required)
     * @param  \OpenAPI\Client\Model\UserUserUpdate $user_user_update The updated user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdPatch'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UserJsonldUserEmpty, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiUsersIdPatchWithHttpInfo(
        string $id,
        \OpenAPI\Client\Model\UserUserUpdate $user_user_update,
        string $contentType = self::contentTypes['apiUsersIdPatch'][0]
    ): array
    {
        $request = $this->apiUsersIdPatchRequest($id, $user_user_update, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if (in_array('\OpenAPI\Client\Model\UserJsonldUserEmpty', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\UserJsonldUserEmpty' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\UserJsonldUserEmpty', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\UserJsonldUserEmpty';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\UserJsonldUserEmpty',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiUsersIdPatchAsync
     *
     * Updates the user resource.
     *
     * @param  string $id user identifier (required)
     * @param  \OpenAPI\Client\Model\UserUserUpdate $user_user_update The updated user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdPatch'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersIdPatchAsync(
        string $id,
        \OpenAPI\Client\Model\UserUserUpdate $user_user_update,
        string $contentType = self::contentTypes['apiUsersIdPatch'][0]
    ): PromiseInterface
    {
        return $this->apiUsersIdPatchAsyncWithHttpInfo($id, $user_user_update, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiUsersIdPatchAsyncWithHttpInfo
     *
     * Updates the user resource.
     *
     * @param  string $id user identifier (required)
     * @param  \OpenAPI\Client\Model\UserUserUpdate $user_user_update The updated user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdPatch'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersIdPatchAsyncWithHttpInfo(
        string $id,
        \OpenAPI\Client\Model\UserUserUpdate $user_user_update,
        string $contentType = self::contentTypes['apiUsersIdPatch'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\UserJsonldUserEmpty';
        $request = $this->apiUsersIdPatchRequest($id, $user_user_update, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiUsersIdPatch'
     *
     * @param  string $id user identifier (required)
     * @param  \OpenAPI\Client\Model\UserUserUpdate $user_user_update The updated user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersIdPatch'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiUsersIdPatchRequest(
        string $id,
        \OpenAPI\Client\Model\UserUserUpdate $user_user_update,
        string $contentType = self::contentTypes['apiUsersIdPatch'][0]
    ): Request
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $id when calling apiUsersIdPatch'
            );
        }

        // verify the required parameter 'user_user_update' is set
        if ($user_user_update === null || (is_array($user_user_update) && count($user_user_update) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $user_user_update when calling apiUsersIdPatch'
            );
        }


        $resourcePath = '/api/users/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($user_user_update)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($user_user_update));
            } else {
                $httpBody = $user_user_update;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiUsersPost
     *
     * Creates a user resource.
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\UserJsonldUserEmpty
     */
    public function apiUsersPost(
        \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create,
        string $contentType = self::contentTypes['apiUsersPost'][0]
    ): \OpenAPI\Client\Model\UserJsonldUserEmpty
    {
        list($response) = $this->apiUsersPostWithHttpInfo($user_jsonld_user_create, $contentType);
        return $response;
    }

    /**
     * Operation apiUsersPostWithHttpInfo
     *
     * Creates a user resource.
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UserJsonldUserEmpty, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiUsersPostWithHttpInfo(
        \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create,
        string $contentType = self::contentTypes['apiUsersPost'][0]
    ): array
    {
        $request = $this->apiUsersPostRequest($user_jsonld_user_create, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if (in_array('\OpenAPI\Client\Model\UserJsonldUserEmpty', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\UserJsonldUserEmpty' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\UserJsonldUserEmpty', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\UserJsonldUserEmpty';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\UserJsonldUserEmpty',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiUsersPostAsync
     *
     * Creates a user resource.
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersPostAsync(
        \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create,
        string $contentType = self::contentTypes['apiUsersPost'][0]
    ): PromiseInterface
    {
        return $this->apiUsersPostAsyncWithHttpInfo($user_jsonld_user_create, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiUsersPostAsyncWithHttpInfo
     *
     * Creates a user resource.
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersPostAsyncWithHttpInfo(
        \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create,
        string $contentType = self::contentTypes['apiUsersPost'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\UserJsonldUserEmpty';
        $request = $this->apiUsersPostRequest($user_jsonld_user_create, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiUsersPost'
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiUsersPostRequest(
        \OpenAPI\Client\Model\UserJsonldUserCreate $user_jsonld_user_create,
        string $contentType = self::contentTypes['apiUsersPost'][0]
    ): Request
    {

        // verify the required parameter 'user_jsonld_user_create' is set
        if ($user_jsonld_user_create === null || (is_array($user_jsonld_user_create) && count($user_jsonld_user_create) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $user_jsonld_user_create when calling apiUsersPost'
            );
        }


        $resourcePath = '/api/users';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($user_jsonld_user_create)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($user_jsonld_user_create));
            } else {
                $httpBody = $user_jsonld_user_create;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiUsersresendActivationPost
     *
     * Resend activation email
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresendActivationPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\UserJsonld
     */
    public function apiUsersresendActivationPost(
        \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation,
        string $contentType = self::contentTypes['apiUsersresendActivationPost'][0]
    ): \OpenAPI\Client\Model\UserJsonld
    {
        list($response) = $this->apiUsersresendActivationPostWithHttpInfo($user_jsonld_user_resend_activation, $contentType);
        return $response;
    }

    /**
     * Operation apiUsersresendActivationPostWithHttpInfo
     *
     * Resend activation email
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresendActivationPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UserJsonld, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiUsersresendActivationPostWithHttpInfo(
        \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation,
        string $contentType = self::contentTypes['apiUsersresendActivationPost'][0]
    ): array
    {
        $request = $this->apiUsersresendActivationPostRequest($user_jsonld_user_resend_activation, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if (in_array('\OpenAPI\Client\Model\UserJsonld', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\UserJsonld' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\UserJsonld', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\UserJsonld';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\UserJsonld',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiUsersresendActivationPostAsync
     *
     * Resend activation email
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresendActivationPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersresendActivationPostAsync(
        \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation,
        string $contentType = self::contentTypes['apiUsersresendActivationPost'][0]
    ): PromiseInterface
    {
        return $this->apiUsersresendActivationPostAsyncWithHttpInfo($user_jsonld_user_resend_activation, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiUsersresendActivationPostAsyncWithHttpInfo
     *
     * Resend activation email
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresendActivationPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersresendActivationPostAsyncWithHttpInfo(
        \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation,
        string $contentType = self::contentTypes['apiUsersresendActivationPost'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\UserJsonld';
        $request = $this->apiUsersresendActivationPostRequest($user_jsonld_user_resend_activation, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiUsersresendActivationPost'
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresendActivationPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiUsersresendActivationPostRequest(
        \OpenAPI\Client\Model\UserJsonldUserResendActivation $user_jsonld_user_resend_activation,
        string $contentType = self::contentTypes['apiUsersresendActivationPost'][0]
    ): Request
    {

        // verify the required parameter 'user_jsonld_user_resend_activation' is set
        if ($user_jsonld_user_resend_activation === null || (is_array($user_jsonld_user_resend_activation) && count($user_jsonld_user_resend_activation) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $user_jsonld_user_resend_activation when calling apiUsersresendActivationPost'
            );
        }


        $resourcePath = '/api/users/resend-activation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($user_jsonld_user_resend_activation)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($user_jsonld_user_resend_activation));
            } else {
                $httpBody = $user_jsonld_user_resend_activation;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiUsersresetPasswordPost
     *
     * Reset password (with token)
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresetPasswordPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\UserJsonldUserEmpty
     */
    public function apiUsersresetPasswordPost(
        \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password,
        string $contentType = self::contentTypes['apiUsersresetPasswordPost'][0]
    ): \OpenAPI\Client\Model\UserJsonldUserEmpty
    {
        list($response) = $this->apiUsersresetPasswordPostWithHttpInfo($user_jsonld_user_reset_password, $contentType);
        return $response;
    }

    /**
     * Operation apiUsersresetPasswordPostWithHttpInfo
     *
     * Reset password (with token)
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresetPasswordPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UserJsonldUserEmpty, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiUsersresetPasswordPostWithHttpInfo(
        \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password,
        string $contentType = self::contentTypes['apiUsersresetPasswordPost'][0]
    ): array
    {
        $request = $this->apiUsersresetPasswordPostRequest($user_jsonld_user_reset_password, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if (in_array('\OpenAPI\Client\Model\UserJsonldUserEmpty', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\UserJsonldUserEmpty' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\UserJsonldUserEmpty', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\UserJsonldUserEmpty';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\UserJsonldUserEmpty',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiUsersresetPasswordPostAsync
     *
     * Reset password (with token)
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresetPasswordPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersresetPasswordPostAsync(
        \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password,
        string $contentType = self::contentTypes['apiUsersresetPasswordPost'][0]
    ): PromiseInterface
    {
        return $this->apiUsersresetPasswordPostAsyncWithHttpInfo($user_jsonld_user_reset_password, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiUsersresetPasswordPostAsyncWithHttpInfo
     *
     * Reset password (with token)
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresetPasswordPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUsersresetPasswordPostAsyncWithHttpInfo(
        \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password,
        string $contentType = self::contentTypes['apiUsersresetPasswordPost'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\UserJsonldUserEmpty';
        $request = $this->apiUsersresetPasswordPostRequest($user_jsonld_user_reset_password, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiUsersresetPasswordPost'
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUsersresetPasswordPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiUsersresetPasswordPostRequest(
        \OpenAPI\Client\Model\UserJsonldUserResetPassword $user_jsonld_user_reset_password,
        string $contentType = self::contentTypes['apiUsersresetPasswordPost'][0]
    ): Request
    {

        // verify the required parameter 'user_jsonld_user_reset_password' is set
        if ($user_jsonld_user_reset_password === null || (is_array($user_jsonld_user_reset_password) && count($user_jsonld_user_reset_password) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $user_jsonld_user_reset_password when calling apiUsersresetPasswordPost'
            );
        }


        $resourcePath = '/api/users/reset-password';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($user_jsonld_user_reset_password)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($user_jsonld_user_reset_password));
            } else {
                $httpBody = $user_jsonld_user_reset_password;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiUserssendResetPasswordPost
     *
     * Send reset password email
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUserssendResetPasswordPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \OpenAPI\Client\Model\UserJsonldUserEmpty
     */
    public function apiUserssendResetPasswordPost(
        \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password,
        string $contentType = self::contentTypes['apiUserssendResetPasswordPost'][0]
    ): \OpenAPI\Client\Model\UserJsonldUserEmpty
    {
        list($response) = $this->apiUserssendResetPasswordPostWithHttpInfo($user_jsonld_user_send_reset_password, $contentType);
        return $response;
    }

    /**
     * Operation apiUserssendResetPasswordPostWithHttpInfo
     *
     * Send reset password email
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUserssendResetPasswordPost'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UserJsonldUserEmpty, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiUserssendResetPasswordPostWithHttpInfo(
        \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password,
        string $contentType = self::contentTypes['apiUserssendResetPasswordPost'][0]
    ): array
    {
        $request = $this->apiUserssendResetPasswordPostRequest($user_jsonld_user_send_reset_password, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if (in_array('\OpenAPI\Client\Model\UserJsonldUserEmpty', ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\UserJsonldUserEmpty' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\UserJsonldUserEmpty', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Model\UserJsonldUserEmpty';
            if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\UserJsonldUserEmpty',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiUserssendResetPasswordPostAsync
     *
     * Send reset password email
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUserssendResetPasswordPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUserssendResetPasswordPostAsync(
        \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password,
        string $contentType = self::contentTypes['apiUserssendResetPasswordPost'][0]
    ): PromiseInterface
    {
        return $this->apiUserssendResetPasswordPostAsyncWithHttpInfo($user_jsonld_user_send_reset_password, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiUserssendResetPasswordPostAsyncWithHttpInfo
     *
     * Send reset password email
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUserssendResetPasswordPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function apiUserssendResetPasswordPostAsyncWithHttpInfo(
        \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password,
        string $contentType = self::contentTypes['apiUserssendResetPasswordPost'][0]
    ): PromiseInterface
    {
        $returnType = '\OpenAPI\Client\Model\UserJsonldUserEmpty';
        $request = $this->apiUserssendResetPasswordPostRequest($user_jsonld_user_send_reset_password, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiUserssendResetPasswordPost'
     *
     * @param  \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password The new user resource (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiUserssendResetPasswordPost'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiUserssendResetPasswordPostRequest(
        \OpenAPI\Client\Model\UserJsonldUserSendResetPassword $user_jsonld_user_send_reset_password,
        string $contentType = self::contentTypes['apiUserssendResetPasswordPost'][0]
    ): Request
    {

        // verify the required parameter 'user_jsonld_user_send_reset_password' is set
        if ($user_jsonld_user_send_reset_password === null || (is_array($user_jsonld_user_send_reset_password) && count($user_jsonld_user_send_reset_password) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $user_jsonld_user_send_reset_password when calling apiUserssendResetPasswordPost'
            );
        }


        $resourcePath = '/api/users/send-reset-password';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/ld+json', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($user_jsonld_user_send_reset_password)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($user_jsonld_user_send_reset_password));
            } else {
                $httpBody = $user_jsonld_user_send_reset_password;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
